# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ROOT_DIR": "00_core.ipynb",
         "DOWNLOAD_DIR_BASE": "00_core.ipynb",
         "PROCESSED_DIR_BASE": "00_core.ipynb",
         "DATASET_DIR": "00_core.ipynb",
         "create_country_dirs": "00_core.ipynb",
         "gen_weekdates": "00_core.ipynb",
         "STANDARD_WEEK": "00_core.ipynb",
         "STANDARD_WEEK.columns": "00_core.ipynb",
         "LAST_MODIFIED": "020_Netherlands.ipynb",
         "COUNTRIES": "03_collect.ipynb",
         "SUMMARY": "03_collect.ipynb"}

modules = ["core.py",
           "countries/uk.py",
           "countries/netherlands.py",
           "collect.py"]

doc_url = "https://kk1694.github.io/weekly_mort/"

git_url = "https://github.com/kk1694/weekly_mort/tree/master/"

def custom_doc_links(name): return None
