# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/020_Netherlands.ipynb (unless otherwise specified).

__all__ = ['LAST_MODIFIED']

# Cell
from ..imports import *
from ..core import *

# Cell
LAST_MODIFIED = datetime.date(2020, 4, 21)
LAST_MODIFIED