# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/010_UK.ipynb (unless otherwise specified).

__all__ = ['LAST_MODIFIED']

# Cell
from ..imports import *
from ..core import *

import openpyxl

# Cell
LAST_MODIFIED = datetime.date.today()